### PR TITLE
Never persist "Add a placeholder" to store, fixes #1

### LINKED ISSUE #1: Default placeholder in exported state
The default placeholder _Insert a placeholder text_ should never show up in the state object dispatched with the `formBuilderSave` event.

### PR DESCRIPTION
**Pull request by foaly-nr1**

### CODE REVIEW

**Comment by foaly-nr1** [comment]
@lazamar any idea why [the test I mutated](https://github.com/fourlabsldn/fl-form-builder/pull/5/commits/2c58db8e7bf2a78d5fe4ce2c51b49b778b10dbe8) didn't fail? It looks like a lot of tests are never executed.

**Comment by lazamar** [comment]
Seems that is because of this: https://github.com/fourlabsldn/fl-form-builder/blob/placeholder/gulpfile.js#L42-L44

The test src must be the test files, rather than the compiled source.

**Comment by lazamar** [comment]
Actually, no. Forget what I said.

**Comment by lazamar** [comment]
Maybe the reason is that you must first transpile the tests, to then run them.

Try this and see if it will run all tests:
```
gulp transpile-react:tests && gulp test-headless
```

**Comment by foaly-nr1** [comment]
Perfect, thanks!

**Comment by foaly-nr1** [comment]
@lazamar Babel has suddenly started joking on JSX. Can you help?

**Comment by foaly-nr1** [comment]
Broken:
```bash
yarn install
yarn test
```

Works:
```bash
npm install
npm test
```

🤷‍♂️

**Pull request merged**
